name: Publish ImagePorter Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'v2026.1.12.3'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: imageporter
        password: ${{ secrets.DockerHub_TOKEN }}

    - name: Login to GitHub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: stable
        cache: false

    - name: Build tools
      shell: bash
      run: |
        set -euo pipefail

        for arch in amd64 arm64; do
          export GOOS=linux
          export GOARCH="${arch}"
          export GOBIN="${PWD}/bin/${GOOS}_${GOARCH}"

          mkdir -p "${GOBIN}"
          go install github.com/google/go-containerregistry/cmd/crane@v0.20.7
          go install github.com/aptible/supercronic@v0.2.41
          chmod +x "${GOBIN}/crane" "${GOBIN}/supercronic"
        done

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          imageporter/imageporter:${{ inputs.tag }}
          imageporter/imageporter:latest
          ghcr.io/imageporter/imageporter:${{ inputs.tag }}
          ghcr.io/imageporter/imageporter:latest

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.tag }}
